source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 2.0'
pod 'SDWebImage', '~>3.7'
pod 'SCLAlertView-Objective-C'
pod 'EAIntroView', '~> 2.7.0'
pod 'PNChart'
pod 'UICountingLabel'
pod 'BXProgressHUD'

pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

end